trigger:
- master

pool:
  name: 'SelfHostedCruise'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install --save-dev nyc
    npm install --save-dev mocha-junit-reporter
  displayName: 'npm install and install dev dependencies'

- script: |
    npx nyc npm test
  displayName: 'npm test with coverage'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
